import { transactionCategory } from "@/db/schema";
import { autoGeneratedColumns } from "@/db/utils/shared";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

export const insertTransactionCategorySchema =
  createInsertSchema(transactionCategory).omit(autoGeneratedColumns);

export const transactionCategoryInputSchema = z.object({
  name: z.string().min(1, "Name is required"),
  description: z.string().nullable().optional(),
  type: z.enum(["MONEY_IN", "MONEY_OUT"]),
  isSystem: z.boolean().optional().default(false),
  // displayPriority is now directly on transactionCategory and is optional
  displayPriority: z.number().int().nullable().optional(),
});

export const createTransactionCategorySchema = transactionCategoryInputSchema;
export const updateTransactionCategorySchema =
  transactionCategoryInputSchema.partial();

// Removed transactionCategoryPrecedence related schemas and types as displayPriority is now on transactionCategory itself.

export type CreateTransactionCategoryDto = z.infer<
  typeof createTransactionCategorySchema
>;
export type UpdateTransactionCategoryDto = z.infer<
  typeof updateTransactionCategorySchema
>;
// Removed PrecedenceUpdateDto and BulkPrecedenceUpdateDto
